version: '3.7'
services:
  mongodb:
    image: mongo:4.4.6
    ports:
      - '27017:27017'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pwd
